spring:
  profiles:
    default: local

  #  datasource:
  #    url: jdbc:h2:mem:~/ChallengeApplication
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:[forwardedPort]/${DB_SCHEMA_NAME}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

ssh:
  remote_jump_host: ${EC2_IP}
  ssh_port: 22
  user: ubuntu
  private_key: ${EC2_PRIVATE_KEY_PATH}
  database_url: ${DB_URL}
  database_port: 3306

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
