spring:
  profiles:
    default: local

social:
  kakao:
    apikey: ${KAKAO_API_KEY}
    redirect_uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access_expiration_time: 36000000 # 10시간 (10 * 60 * 60 * 1000 밀리초)
  refresh_expiration_day: 14 # 2주

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    S3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

---
# 로컬 환경
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mysql://127.0.0.1:[forwardedPort]/${DB_SCHEMA_NAME}?useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

ssh:
  remote_jump_host: ${EC2_IP}
  ssh_port: 22
  user: ubuntu
  private_key: ${EC2_PRIVATE_KEY_PATH}
  database_url: ${DB_URL}
  database_port: 3306

---
# 개발 환경
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://${RDS_PRIVATE_IP}:${RDS_PORT}/${DB_SCHEMA_NAME}?useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

social:
  kakao:
    apikey: ${KAKAO_API_KEY}
    redirect_uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access_expiration_time: 36000000 # 10시간 (10 * 60 * 60 * 1000 밀리초)
  refresh_expiration_day: 14 # 2주

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    S3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
