name: Challenge CI/CD Pipeline

#on:
#  pull_request:
#    branches:
#      - dev
#      - main
on:
  push:
    branches:
      - feat/6

jobs:
  build-and-deploy: # Job 이름
    runs-on: ubuntu-latest # 실행 환경 - 가장 최신 버전의 Ubuntu 환경

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Docker 확장 기능 추가
        uses: docker/setup-buildx-action@v3

      - name: 도커 허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push
        uses: docker/build-push-action@v6
        with:
          context: . # Dockerfile 위치
          file: ./Dockerfile # Dockerfile 경로
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenge:${{GITHUB_SHA}} # 이미지 태그
          platforms: linux/amd64,linux/arm64
